### ISSUE TITLE
Access Control Exception with Security Manager

### ISSUE THREAD

**Issue by copperleaf91** [openjsse/openjsse#10]
We enable the java SecurityManager when running our application. After adding the openjsse jar, we are seeing the following stacktrace. We can get around it (partially) by wrapping our call to SSLContext.getinstance() in a doPrivileged block, but there may be cases (like with Jetty) or other third party components that legitimately may need to create a security context, may not. I think it makes sense for the openjsse implementation to add the doPrivileged blocks in SSLContextImpl call to getCustomizedCipherSuites.

What do you all think?

```
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.action")
        at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
        at java.security.AccessController.checkPermission(AccessController.java:886)
        at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
        at java.lang.SecurityManager.checkPackageAccess(SecurityManager.java:1564)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:329)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.openjsse.sun.security.ssl.SSLContextImpl.getCustomizedCipherSuites(SSLContextImpl.java:466)
        at org.openjsse.sun.security.ssl.SSLContextImpl.<clinit>(SSLContextImpl.java:107)
        ... 40 more
```

**Comment by copperleaf91** [comment]
Looking at the source some, it appears that even though the call to GetPropertyAction.privilegedGetProperty internally has a doPrivileged block, the loading of the GetPropertyAction class is actually causing the exception. Our thoughts are to wrap the line
`String property = GetPropertyAction.privilegedGetProperty(propname);`
in a doPrivileged block. Probably also need to apply to the same call in the populate method.

**Comment by copperleaf91** [comment]
Some more info. It appears that this occurs in many places. I'm going through on a copy in my repo and seeing how many (and how easy) it is to fix. If successful, I will post a pull request for you all to look at, etc. In the meantime, in an attempt to see if our code works at all, I've disabled the security manager in my dev instance and have been able to perform client and server connections with openjsse and TLS 1.3. While debugging, I ran across a couple of exceptions while starting our server instances. Below are the stack traces I'm seeing. Note, I only see them when 

`-Djavax.net.debug=ssl:handshake`

is passed in, so I suspect that it's just debugging noise. Can you confirm this?

```
javax.net.ssl|DEBUG|03|Finalizer|2019-09-17 11:20:24.015 EDT|SSLSocketImpl.java:499|duplex close of SSLSocket
javax.net.ssl|WARNING|03|Finalizer|2019-09-17 11:20:24.019 EDT|SSLSocketImpl.java:520|SSLSocket duplex close failed (
"throwable" : {
  java.net.SocketException: Socket is not connected
        at java.net.Socket.shutdownOutput(Socket.java:1553)
        at org.openjsse.sun.security.ssl.BaseSSLSocketImpl.shutdownOutput(BaseSSLSocketImpl.java:233)
        at org.openjsse.sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:587)
        at org.openjsse.sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:505)
        at org.openjsse.sun.security.ssl.BaseSSLSocketImpl.finalize(BaseSSLSocketImpl.java:276)
        at java.lang.System$2.invokeFinalize(System.java:1270)
        at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:102)
        at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:217)}

)
javax.net.ssl|DEBUG|03|Finalizer|2019-09-17 11:20:24.020 EDT|SSLSocketImpl.java:499|duplex close of SSLSocket
javax.net.ssl|WARNING|03|Finalizer|2019-09-17 11:20:24.022 EDT|SSLSocketImpl.java:520|SSLSocket duplex close failed (
"throwable" : {
  java.net.SocketException: Socket is not connected
        at java.net.Socket.shutdownOutput(Socket.java:1553)
        at org.openjsse.sun.security.ssl.BaseSSLSocketImpl.shutdownOutput(BaseSSLSocketImpl.java:233)
        at org.openjsse.sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:587)
        at org.openjsse.sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:505)
        at org.openjsse.sun.security.ssl.BaseSSLSocketImpl.finalize(BaseSSLSocketImpl.java:276)
        at java.lang.System$2.invokeFinalize(System.java:1270)
        at java.lang.ref.Finalizer.runFinalizer(Finalizer.java:102)
        at java.lang.ref.Finalizer.access$100(Finalizer.java:34)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:217)}

)

```

**Comment by gstanchev** [comment]
Is this in Tomcat? I asked the same question on the Tomcat mailing list [1] but nobody responded. We are seeing the same issue.


[1] https://mail-archives.apache.org/mod_mbox/tomcat-users/201908.mbox/%3CBYAPR18MB2598EDADA8211129C902018E80D50%40BYAPR18MB2598.namprd18.prod.outlook.com%3E

**Comment by copperleaf91** [comment]
No, it's in a custom framework called Niagara. We use our own socket factory stack with jetty and some custom ip protocols.

**Comment by copperleaf91** [comment]
Some more discoveries. SslSocket.getInputStream has different behavior than it's standard jsse equivalent in Java 8. With openjsse, it throws an IOException. Standard Java returns an object and doesn't throw an exception (an SSLException) until a method on the stream is called. While the IOException makes sense, it broke our code.

**Comment by copperleaf91** [comment]
I've made some progress here. In order for openjsse to play nice with the SecurityManager, it but be loaded on the bootclasspath. This makes sense because, in essence, that is what sunjsse does. The issue remaining now, is when I try and connect to a legacy device (one running sunjsse in 1.8), I get the following on the client side of the connection.

```
Caused by: java.security.InvalidAlgorithmParameterException: TlsMasterSecretGenerator must be initialized using a TlsMasterSecretParameterSpec
        at com.sun.crypto.provider.TlsMasterSecretGenerator.engineInit(TlsMasterSecretGenerator.java:63)
        at javax.crypto.KeyGenerator.init(KeyGenerator.java:454)
        at javax.crypto.KeyGenerator.init(KeyGenerator.java:430)
        at org.openjsse.sun.security.ssl.SSLMasterKeyDerivation$LegacyMasterKeyDerivation.deriveKey(SSLMasterKeyDerivation.java:149)
```

**Comment by copperleaf91** [comment]
Just to keep the various issues clear, I'm closing this one and will open one with the TlsMasterSecretGenerator issue.
