### ISSUE TITLE
Seems the tls connection reading with tls1.2 and writing with tls1.3

### ISSUE THREAD

**Issue by anthonyhu81** [openjsse/openjsse#16]
I'm using Openjsse to replace the default ssl provider in JDK8 for Tomcat9 and my client application(CXF). Only specified TLSv1.3 in client side.
But in Tomcat log file, seems the client send tlsv1.2 handshake to Tomcat, but the tlsv13 is used after negotiation. (Data transfer between client and tomcat is OK.)
However Tomcat seemed to read with tls1.2 since the following log:
        javax.net.ssl|DEBUG|91|https-jsse-nio-21230-exec-8|2020-05-22 10:43:39.504 CST|SSLEngineInputRecord.java:215|READ: TLSv1.2 handshake, length = 270
        javax.net.ssl|DEBUG|8D|https-jsse-nio-21230-exec-4|2020-05-22 10:43:21.782 CST|SSLEngineInputRecord.java:215|READ: TLSv1.2 change_cipher_spec, length = 1
        javax.net.ssl|DEBUG|8E|https-jsse-nio-21230-exec-5|2020-05-22 10:43:21.928 CST|SSLEngineInputRecord.java:215|READ: TLSv1.2 application_data, length = 85

and writing with tls1.3:
        javax.net.ssl|DEBUG|8A|https-jsse-nio-21230-exec-1|2020-05-22 10:43:21.714 CST|SSLEngineOutputRecord.java:505|WRITE: TLS13 handshake, length = 155
        javax.net.ssl|DEBUG|8B|https-jsse-nio-21230-exec-2|2020-05-22 10:43:21.717 CST|SSLEngineOutputRecord.java:505|WRITE: TLS13 change_cipher_spec, length = 1
        javax.net.ssl|DEBUG|8F|https-jsse-nio-21230-exec-6|2020-05-22 10:43:22.941 CST|SSLEngineOutputRecord.java:266|WRITE: TLS13 application_data, length = 16367

 following is the logs for clienthello:

_javax.net.ssl|DEBUG|8A|https-jsse-nio-21230-exec-1|2020-05-22 10:43:21.437 CST|SSLEngineInputRecord.java:215|READ: TLSv1.2 handshake, length = 270
javax.net.ssl|WARNING|8A|https-jsse-nio-21230-exec-1|2020-05-22 10:43:21.455 CST|SupportedGroupsExtension.java:365|No AlgorithmParameters for x25519 (
"throwable" : {
  java.security.NoSuchAlgorithmException: Algorithm x25519 not available
  	at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:184)
  	at org.openjsse.sun.security.ssl.SupportedGroupsExtension$NamedGroup.<init>(SupportedGroupsExtension.java:354)
  	at org.openjsse.sun.security.ssl.SupportedGroupsExtension$NamedGroup.<init>(SupportedGroupsExtension.java:387)
  	at org.openjsse.sun.security.ssl.SupportedGroupsExtension$NamedGroup.<clinit>(SupportedGroupsExtension.java:272)
  	at org.openjsse.sun.security.ssl.SupportedGroupsExtension$SupportedGroups.<clinit>(SupportedGroupsExtension.java:585)
  	at org.openjsse.sun.security.ssl.SupportedGroupsExtension.<clinit>(SupportedGroupsExtension.java:64)
  	at org.openjsse.sun.security.ssl.SSLExtension.<clinit>(SSLExtension.java:138)
  	at org.openjsse.sun.security.ssl.SSLConfiguration.getEnabledExtensions(SSLConfiguration.java:344)
  	at org.openjsse.sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:802)
  	at org.openjsse.sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
  	at org.openjsse.sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
  	at org.openjsse.sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1097)
  	at org.openjsse.sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1084)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at org.openjsse.sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1031)
  	at org.apache.tomcat.util.net.SecureNioChannel.tasks(SecureNioChannel.java:443)
  	at org.apache.tomcat.util.net.SecureNioChannel.handshakeUnwrap(SecureNioChannel.java:507)
  	at org.apache.tomcat.util.net.SecureNioChannel.handshake(SecureNioChannel.java:238)
  	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
  	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  	at java.lang.Thread.run(Thread.java:748)}

)
javax.net.ssl|WARNING|8A|https-jsse-nio-21230-exec-1|2020-05-22 10:43:21.455 CST|SupportedGroupsExtension.java:365|No AlgorithmParameters for x448 (
"throwable" : {
  java.security.NoSuchAlgorithmException: Algorithm x448 not available
  	at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:184)
  	at org.openjsse.sun.security.ssl.SupportedGroupsExtension$NamedGroup.<init>(SupportedGroupsExtension.java:354)
  	at org.openjsse.sun.security.ssl.SupportedGroupsExtension$NamedGroup.<init>(SupportedGroupsExtension.java:387)
  	at org.openjsse.sun.security.ssl.SupportedGroupsExtension$NamedGroup.<clinit>(SupportedGroupsExtension.java:275)
  	at org.openjsse.sun.security.ssl.SupportedGroupsExtension$SupportedGroups.<clinit>(SupportedGroupsExtension.java:585)
  	at org.openjsse.sun.security.ssl.SupportedGroupsExtension.<clinit>(SupportedGroupsExtension.java:64)
  	at org.openjsse.sun.security.ssl.SSLExtension.<clinit>(SSLExtension.java:138)
  	at org.openjsse.sun.security.ssl.SSLConfiguration.getEnabledExtensions(SSLConfiguration.java:344)
  	at org.openjsse.sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:802)
  	at org.openjsse.sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
  	at org.openjsse.sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
  	at org.openjsse.sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1097)
  	at org.openjsse.sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1084)
  	at java.security.AccessController.doPrivileged(Native Method)
  	at org.openjsse.sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:1031)
  	at org.apache.tomcat.util.net.SecureNioChannel.tasks(SecureNioChannel.java:443)
  	at org.apache.tomcat.util.net.SecureNioChannel.handshakeUnwrap(SecureNioChannel.java:507)
  	at org.apache.tomcat.util.net.SecureNioChannel.handshake(SecureNioChannel.java:238)
  	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
  	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  	at java.lang.Thread.run(Thread.java:748)}

)
javax.net.ssl|WARNING|8A|https-jsse-nio-21230-exec-1|2020-05-22 10:43:21.501 CST|SignatureScheme.java:291|Signature algorithm, ed25519, is not supported by the underlying providers
javax.net.ssl|WARNING|8A|https-jsse-nio-21230-exec-1|2020-05-22 10:43:21.502 CST|SignatureScheme.java:291|Signature algorithm, ed448, is not supported by the underlying providers
javax.net.ssl|DEBUG|8A|https-jsse-nio-21230-exec-1|2020-05-22 10:43:21.512 CST|ClientHello.java:808|Consuming ClientHello handshake message (
"ClientHello": {
  "client version"      : "TLSv1.2",
  "random"              : "EC 0D 8E 9E C8 D5 3D 93 72 58 2D F6 48 FF DB 9D 62 C5 6B 12 67 13 DB 2F F8 B9 FB FB AB 13 8D 34",
  "session id"          : "98 E6 44 54 F7 94 C8 DE 2D D6 FA AB 12 F3 FA 10 7A FA 91 38 8E BC 4B AA 8C C6 F8 33 C5 98 97 3E",
  "cipher suites"       : "[TLS_AES_256_GCM_SHA384(0x1302), TLS_AES_128_GCM_SHA256(0x1301), TLS_CHACHA20_POLY1305_SHA256(0x1303)]",
  "compression methods" : "00",
  "extensions"          : [
    "status_request (5)": {
      "certificate status type": ocsp
      "OCSP status request": {
        "responder_id": <empty>
        "request extensions": {
          <empty>
        }
      }
    },
    "supported_groups (10)": {
      "versions": [secp256r1, secp384r1, secp521r1, ffdhe2048, ffdhe3072, ffdhe4096, ffdhe6144, ffdhe8192]
    },
    "signature_algorithms (13)": {
      "signature schemes": [ecdsa_secp256r1_sha256, ecdsa_secp384r1_sha384, ecdsa_secp521r1_sha512, rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, ecdsa_sha1, rsa_pkcs1_sha1]
    },
    "signature_algorithms_cert (50)": {
      "signature schemes": [ecdsa_secp256r1_sha256, ecdsa_secp384r1_sha384, ecdsa_secp521r1_sha512, rsa_pss_rsae_sha256, rsa_pss_rsae_sha384, rsa_pss_rsae_sha512, rsa_pss_pss_sha256, rsa_pss_pss_sha384, rsa_pss_pss_sha512, rsa_pkcs1_sha256, rsa_pkcs1_sha384, rsa_pkcs1_sha512, ecdsa_sha1, rsa_pkcs1_sha1]
    },
    "supported_versions (43)": {
      "versions": [TLSv1.3]
    },
    "psk_key_exchange_modes (45)": {
      "ke_modes": [psk_dhe_ke]
    },
    "key_share (51)": {
      "client_shares": [  
        {
          "named group": secp256r1
          "key_exchange": {
            0000: 04 85 C2 83 D3 B8 03 65   A3 F3 D3 FD 8A 1E 89 E9  .......e........
            0010: 14 15 0D 70 74 82 3D 0F   C8 18 64 19 91 62 92 AD  ...pt.=...d..b..
            0020: 3A DD DF 1D 23 B7 E5 A3   E1 EE 25 37 19 E4 73 AC  :...#.....%7..s.
            0030: 5B 0E 5A D1 A9 DE 4D 64   5A 53 CC 2D EF 48 B6 EC  [.Z...MdZS.-.H..
            0040: 6E 
          }
        },
      ]
    }
  ]
}
)
javax.net.ssl|DEBUG|8A|https-jsse-nio-21230-exec-1|2020-05-22 10:43:21.512 CST|SSLExtensions.java:189|Consumed extension: supported_versions
javax.net.ssl|DEBUG|8A|https-jsse-nio-21230-exec-1|2020-05-22 10:43:21.512 CST|ClientHello.java:838|Negotiated protocol version: TLSv1.3_

Does this mean TLSv1.3 is working or the connection is still using TLSv1.2?

Thanks!

**Comment by alexeybakhtin** [comment]
Hello,

Sorry for the late response.
The TLSv1.3 protocol is negotiated and working in the case you described.
The version field in the ClientHello message is defined in the TLSv1.3 specification, section 4.1.2 ( see https://tools.ietf.org/html/rfc8446#section-4.1.2):
      In previous versions of TLS, this field was used for
      version negotiation and represented the highest version number
      supported by the client.  Experience has shown that many servers
      do not properly implement version negotiation, leading to "version
      intolerance" in which the server rejects an otherwise acceptable
      ClientHello with a version number higher than it supports.  In
      TLS 1.3, the client indicates its version preferences in the
      "supported_versions" extension (Section 4.2.1) and the
      legacy_version field MUST be set to 0x0303, which is the version
      number for TLS 1.2.  TLS 1.3 ClientHellos are identified as having
      a legacy_version of 0x0303 and a supported_versions extension
      present with 0x0304 as the highest version indicated therein.
      (See Appendix D for details about backward compatibility.)

Regards
Alexey

**Comment by anthonyhu81** [comment]
@alexeybakhtin  Thanks for your reply!
