### ISSUE TITLE
Error when running with OpenJDK 11

### ISSUE THREAD

**Issue by yschimke** [openjsse/openjsse#6]
From this PR https://github.com/square/okhttp/pull/5382

```
        Caused by:
        java.security.KeyStoreException: problem accessing trust store
            at org.openjsse.sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:78)
            at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
            at org.conscrypt.SSLParametersImpl.createDefaultX509TrustManager(SSLParametersImpl.java:591)
            ... 5 more

            Caused by:
            java.io.IOException: DerInputStream.getLength(): lengthTag=109, too big.
                at java.base/sun.security.util.DerInputStream.getLength(DerInputStream.java:606)
                at java.base/sun.security.util.DerValue.init(DerValue.java:390)
                at java.base/sun.security.util.DerValue.<init>(DerValue.java:331)
                at java.base/sun.security.util.DerValue.<init>(DerValue.java:344)
                at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1993)
                at java.base/java.security.KeyStore.load(KeyStore.java:1479)
                at org.openjsse.sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:365)
                at org.openjsse.sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:313)
                at org.openjsse.sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:55)
                at org.openjsse.sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:54)
                ... 7 more
```

**Comment by yschimke** [comment]
Feel free to close this if it's clearly an OkHTTP test bug.  We try to manage different providers and VMs in some of the tests/builds, so we may not have configured things correctly.

Failure pops up via calls like

```
    SSLSocket socket = (SSLSocket) SSLSocketFactory.getDefault().createSocket();
```

```
  private val provider: Provider = Conscrypt.newProviderBuilder().provideTrustManager(true).build()
  val context: SSLContext = SSLContext.getInstance("TLS", provider)
```

**Comment by alexeybakhtin** [comment]
Hello Yuri,

Configuration of OpenJSSE provider with JDK11 is not supported yet.

**Comment by yschimke** [comment]
@alexeybakhtin what version range is supported? 8-10?

**Comment by alexeybakhtin** [comment]
Currently, JDK8 is supported only
