### ISSUE TITLE
Fails on early JDK 8 versions

### ISSUE THREAD

**Issue by yschimke** [openjsse/openjsse#7]
```
Exception in thread "main" java.lang.NoSuchMethodError: sun.security.action.GetPropertyAction.privilegedGetProperty(Ljava/lang/String;)Ljava/lang/String;
	at org.openjsse.sun.security.ssl.SSLLogger.<clinit>(SSLLogger.java:162)
	at org.openjsse.sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:62)
	at javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:250)
	at okhttp3.internal.platform.OpenJSSEPlatform.platformTrustManager(OpenJSSEPlatform.kt:45)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:219)
	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:955)
	at okhttp3.curl.Main.createClient(Main.kt:176)
	at okhttp3.curl.Main.run(Main.kt:117)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1729)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2101)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2068)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1935)
	at picocli.CommandLine.execute(CommandLine.java:1864)
	at okhttp3.curl.Main$Companion.main(Main.kt:241)
	at okhttp3.curl.Main.main(Main.kt)
```

Maybe just needs minimum versions to be documented.

```
java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

**Comment by alexeybakhtin** [comment]
Hello Yuri,

Current version of OpenJSSE provider is fully compatible with the latest JDK8 version (JDK8u_222). It will be updated for every JDK8 PSU release to insure compatibility between provider and core libraries. 
Compatibility with early versions is possible but not guarantied.
